// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"im-service/app/chat/service/internal/biz"
	"im-service/app/chat/service/internal/conf"
	"im-service/app/chat/service/internal/data"
	"im-service/app/chat/service/internal/server"
	"im-service/app/chat/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(registry *conf.Registry, confMq *conf.RocketMq, confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	redis := data.NewRedisClient(confData)
	producer := data.NewMqProducer(confMq)
	consumer := data.NewMqConsumer(confMq)
	dataData, cleanup, err := data.NewData(redis, producer, consumer, logger)
	if err != nil {
		return nil, nil, err
	}
	wsRepo := data.NewWsRepo(dataData, logger)
	WsUseCase := biz.NewWsUseCase(wsRepo, logger)
	wsService := service.NewWsService(WsUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, wsService, logger)
	httpServer := server.NewHTTPServer(confServer, redis, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}

